services:
  stack-data-uploader:
    image: ghcr.io/theworldavatar/stack-client${IMAGE_SUFFIX}:1.48.0-datasubset-metadata-SNAPSHOT
    secrets:
      - blazegraph_password
      - postgis_password
      - geoserver_password
    volumes:
      - ./inputs/data:/inputs/data:z
      - ./inputs/config:/inputs/config
